### ISSUE TITLE
where is dustjs defined?

### ISSUE THREAD

**Issue by csakis** [krakenjs/adaro#113]
In the README.MD under the 
cache (optional, defaults to true) Boolean
it reads:
```
app.engine('dust', dustjs.dust({ cache: false }));
app.set('view engine', 'dust');
```
However **dustjs** is not defined anywhere. Is that a typo and should it be 
`adaro.dust({ cache: false })`

**Comment by grawk** [comment]
Hi @csakis. I believe that snippet implies that there is a dustjs require statement earlier in the code.
