### ISSUE TITLE
Possible incompatibility node-email-templates/consolidate

### ISSUE THREAD

**Issue by jkennedy1980** [krakenjs/adaro#35]
I was using adaro with express and ran into an issue when I need to render HMTL emails using node-email-templates: https://github.com/niftylettuce/node-email-templates. Adaro/dust works great until after I render a single email. After rendering an email it seems that some global adaro/dust state gets corrupted and it is unable to render any of my regular view templates. node-email-templates uses consolidate so I replaced adaro with consolidate and everything works fine.

**Comment by SergeyG** [comment]
That is because consolidate setup onLoad handler.
After email render completed, I always delete dust.onLoad property and still use adaro

**Comment by aredridel** [comment]
Indeed. New adaro will use their own copy of dust, so that won't happen, but for now, beware. The interface is very global and intended to be mutated.
