### ISSUE TITLE
Support for absolute paths to Helpers?

### ISSUE THREAD

**Issue by kreegr** [krakenjs/adaro#45]
I'd like pass an absolute path to a helper module (from within a subApp).  Is this a bug or by design?

**Comment by aredridel** [comment]
Which bit are you referring to?

A fully qualified path should work.

**Comment by kreegr** [comment]
This may be a misunderstanding on my part.
Line 64 in engine.js has the following comment:

```
// "helpers": ["./lib/abc", { "name": "./lib/test", "arguments": { "debug": true } }] 
```

I'm trying to pass 

```
{
    helpers:['/abs/path/to/helpers']
}
```

However, reqwire.js appends process.cwd() to it (breaks the path)

```
if (~name.indexOf('/')) {
   name = path.join(process.cwd(), name);
}
```

As my breaking pull, shows, I'm guessing there's a conflict here between using names vs paths (was my assumption based on the comment, above).

**Comment by aredridel** [comment]
The `indexOf` check is trying to see if it has a slash at all, not whether it starts with one. So it'd take something more careful than what you changed.

**Comment by kreegr** [comment]
yup - so, relative paths it is.
