### ISSUE TITLE
Adding dust helpers

### ISSUE THREAD

**Issue by GlynnPhillips** [krakenjs/adaro#50]
Hi,

I am not sure I am looking your documentation correctly for adding a new helper, do you have any examples from Kraken where I would be able to see a helper being added?

Thanks

**Comment by jasisk** [comment]
``` js
var express = require('express');
var adaro = require('adaro');

var app = express();
var opts = {
  helpers: [
    './my/helper', // relative paths work
    'dustjs-helpers', // so do installed modules
    {
      name: './my/factory',
      arguments: [ 'an argument' ] // or use this signature if you need to pass in additional args
    }
  ]
};

app.engine('dust', adaro(opts));
app.set('view engine', 'dust');
```

Note that every helper should take the `dust` object as it's first argument. The `arguments` array in the example above will have that object prepended automatically. E.g., the function returned by `./my/factory` will be called with `func(dust, [ 'an argument' ])` (as [per the readme](https://github.com/krakenjs/adaro#helpers-optional-an-array-of-helper-modules-to-require-and-use)).

**Comment by GlynnPhillips** [comment]
Thanks @jasisk I will give this a go asap. Thanks for the quick response

**Comment by jasisk** [comment]
No problem. Closing this out but feel free to continue the conversation if you need any more help.
