### ISSUE TITLE
@eq does not work without @select

### ISSUE THREAD

**Issue by kurdin** [krakenjs/adaro#53]
We use latest dust (2.6.2) and dust helpers (1.6.2) with adaro (0.1.8) in  krakenjs (1.0.3) 
When dust template has `@eq` helper without `@select` html output nothing:

Data:

``` javascript
sessionHelper = {
  "seo": false,
  "timestamp": 1428589929727,
  "port": 3000,
  "user": {}
}
```

This is works as expected:

``` html
{@select key=sessionHelper.seo}
{@eq value="false" type="boolean"}
    <h1>Select + EQ: The this right</h1>
{:else}
    <h1>Select + EQ: This this wrong</h1>
{/eq}
{/select}
```

output: 
`<h1>Select + EQ: The this right</h1>`

And this DOES NOT output anything:

``` html
{@eq key=sessionHelper.seo value="false" type="boolean"}
  <h1>EQ only: The this right</h1>
  {:else}
  <h1>EQ only: This this wrong</h1>
{/eq}
```

I thought this a dust issue, but rendering same code from controller with dust.comple and dust.render will output correct lines in both versions.

Also, I was trying to update `adaro` to latest 2.0.0-x but it wont work with `engine-munger` that requires `"adaro": "~0.1.5"`

Here is an example of working code in pure dust, it works as expected: http://jsfiddle.net/7x4z3766/

**Comment by jasisk** [comment]
I believe this issue is related to linkedin/dustjs-helpers#128.

In the meantime, the workaround is to downgrade to 2.6.1 / 1.6.1. I'll keep this open until there is progress in the dusts-helpers PR.

**Comment by kurdin** [comment]
@jasisk I downgraded to 2.6.1 / 1.6.1. and it wont help. Same problem. But patching dustjs-helpers in lib/dust-helpers.js on line 28 resolves the issue.

https://github.com/rragan/dustjs-helpers/commit/aa230813e80367bfc27d42089f322f653cb68888

Thanks for the tip, waiting on updated version.

**Comment by sethkinast** [comment]
[dustjs-helpers 1.6.3](https://github.com/linkedin/dustjs-helpers/releases/tag/v1.6.3): coming soon to an NPM near you.

**Comment by kurdin** [comment]
@sethkinast Thank you sir!

**Comment by jasisk** [comment]
Seconded. Thanks, @sethkinast!

@kurdin I'll leave this issue open for you to confirm, if you don't mind.

**Comment by sethkinast** [comment]
Published and confirmed on my end.

`npm i --save dustjs-helpers@1.6.3`

**Comment by jasisk** [comment]
Oh my goodness. Sorry, @kurdin. My brain was on autopilot this morning. It's not yours to confirm—that's my job.

Noticed a couple of failures on `dustjs-linkedin@2.6.2` and `dustjs-helpers@1.6.3`. @aredridel is looking into it on `v2.x`. We'll get to the other majors soon.

**Comment by kurdin** [comment]
@jasisk take your time.

**Comment by jasisk** [comment]
v2.x: https://github.com/krakenjs/adaro/pull/55
v0.1.x: https://github.com/krakenjs/adaro/pull/56
