### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by xShirase** [krakenjs/adaro#63]
Hi all,
I cloned my app which runs fine, on a new server, and I get the following error on npm start, any idea where it could come from?

`TypeError: Cannot read property 'name' of undefined
   at applied (/myApp/node_modules/adaro/lib/patch/index.js:121:21)
   at notApplied (/myApp/node_modules/adaro/lib/patch/index.js:126:13)
   at Object.apply (/myApp/node_modules/adaro/lib/patch/index.js:113:13)
   at View.engine (/myApp/node_modules/adaro/lib/engine.js:96:15)
   at View.render (/myApp/node_modules/express/lib/view.js:93:8)
   at EventEmitter.app.render (/myApp/node_modules/express/lib/application.js:566:10)
   at ServerResponse.res.render (/myApp/node_modules/express/lib/response.js:938:7)
   at /myApp/controllers/index.js:16:13
   at Layer.handle [as handle_request] (/myApp/node_modules/express/lib/router/layer.js:82:5)
   at next (/myApp/node_modules/express/lib/router/route.js:110:13)`

The line mentioned in index.js is : 

`res.render('index', model);`

**Comment by xShirase** [comment]
after a bit of research, it turns out that if I copy the node_modules folder of the working app to the not working one, it runs flawlessly, so it's seems to be an issue with the versions.

adaro 0.1.8 runs, not 0.1.9

**Comment by aredridel** [comment]
I bet it's not adaro.

Dust 2.7.0 or 2.6.2?

**Comment by xShirase** [comment]
well played :-)
2.7.4 on npm installing the new folder, 2.6.2 on the old one

**Comment by aredridel** [comment]
Bingo. adaro does not support dust 2.7, and dust does not follow semver. You want to specify "~2.6.2" not "^2.0.0" or anything like that. You have to lock to minor versions.

**Comment by xShirase** [comment]
cool, easy fix.
Does that mean the same thing for any new kraken app, as the package.json of krakenJS says : 
`"dustjs-linkedin": "^2.3.4",`

**Comment by aredridel** [comment]
Yes indeed. I'm still tracking down all the places that gets set.

**Comment by xShirase** [comment]
that too :
`The peer dependency dustjs-linkedin@2.7 - 2.8 included from dustjs-helpers will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.`

**Comment by aredridel** [comment]
Correct: your app must declare the dependency on dustjs-linkedin, not relying on loading the helpers to do it.

**Comment by xShirase** [comment]
I have : 
`"dustjs-helpers": "^1.2.0",
    "dustjs-linkedin": "~2.6.2",`

but npm says :
`Peer dustjs-helpers@1.7.0 wants dustjs-linkedin@2.7 - 2.8`

**Comment by xShirase** [comment]
I manually changed the packages to make it work, but that probably needs to be adressed higher in the "grand scheme of things"

**Comment by aredridel** [comment]
Same thing with dustjs-helpers: You specified version 1.7.0 via "^1.2.0", but it doesn't follow semver. Try "~1.6.0".

**Comment by xShirase** [comment]
installs, builds, and runs ok.
Thanks for your help, fast and efficient as usual

**Comment by aredridel** [comment]
Sure thing! How'd you generate your app, by the way? generator-kraken should use ~ versions as far as I'm aware.

**Comment by xShirase** [comment]
I used generator kraken, but it was a while ago, now the app has evolved a lot, i'm just cloning my repo.
However, the versions in the package.js have to have been auto-generated, I didn't write that.
I'll do a quick test with a fresh generator app, back to you in a minute

**Comment by aredridel** [comment]
Cool! Was just doing the same.

**Comment by aredridel** [comment]
Looks like it generates ^ despite internally requesting ~.

**Comment by xShirase** [comment]
it generates : 
`"dustjs-helpers": "^1.2.0",
    "dustjs-linkedin": "^2.3.6",`

**Comment by aredridel** [comment]
#65 should help address this.

**Comment by aredridel** [comment]
And https://github.com/krakenjs/generator-kraken/issues/163 is the generator issue.
