### ISSUE TITLE
Template Not Found when using partial with root-relative link

### ISSUE THREAD

**Issue by AleCaste** [krakenjs/adaro#64]
We are using adaro 2.0.0-4 with dustjs-linkedin 2.7.0 and dustjs-helpers 1.7.0
The webpage we are trying to render is a dust  template and it renders fine... until we add a partial like this:
{>"/shared/page_ready" /}

Using the above partial throws the following error:

```
Template Not Found: /shared/page_ready

Error: Template Not Found: /shared/page_ready
    at runChain (D:\nodeapps\exp0\node_modules\adaro\node_modules\dustjacket\index.js:56:47)
    at args (D:\nodeapps\exp0\node_modules\adaro\node_modules\dustjacket\index.js:75:32)
    at D:\nodeapps\exp0\node_modules\adaro\lib\engine.js:43:17
    at fs.js:265:20
    at FSReqWrap.oncomplete (fs.js:99:15)
```

Of course, the `page_ready.dust` file exists in the `[views_folder]/shared` folder.
Could you give us a hint about why this error is happening?
Thanks a lot
Alex

**Comment by aredridel** [comment]
Use dust 2.6.x for now. 2.7.0. broke API and isn't supported. (Dustjs does not follow semver: beware.)

I'm working with the dust team to make new integration points for adaro into the future.

**Comment by AleCaste** [comment]
Thanks for the quick response.
We just uninstalled dustjs-linkedin 2.7.0 and dustjs-helpers 1.7.0...
... and installed dustjs-linkedin 2.6.2 and dustjs-helpers 1.6.3
and the error persists.
Could this be related to a configuration option for Adaro we need to set?
(by the way the README.md mentions that there are Config options that can be set, but it does not specify what those are, or at least we could not find them anywhere)
Thanks again

**Comment by aredridel** [comment]
It can!

Can you try without the leading slash on the partial name? Usually dust templates don't do that.

**Comment by AleCaste** [comment]
Yeah... that worked!
But it should not... "shared/page_ready" is a relative path to the folder the current file is stored whereas "/shared/page_ready" is a root-relative path (being root the views folder).
It's ok for now to make this work but I think this should be changed in the future to be consistent to how relative links works in a website.
One extra thing... when we modified the dust file the changes did not showed up so we had to restart the server altogether. I guess this might be due to caching of the dust files. How can we disable caching? (very useful when we are developing)

**Comment by aredridel** [comment]
At the moment, dustjacket always caches, into the dust cache. It's trivial to write a module (or dustjacket loader) that just clears the cache on every call.) I'd do that for now.

The dust 2.7 release threw a wrench in my plans, but the new infrastructure it exposes should make this easier in the future.

**Comment by aredridel** [comment]
Anyway: dust templates have never used relative-to-current-file naming. It's always been a leading`/`-less name from the root. It's not pretty, but plays nice with how `dustc` works.

**Comment by AleCaste** [comment]
Ok, got it. We'll use that naming convention then.
We modified the dustjacket loader to clear the cache in every call and it works.
But it would be better if caching could be controlled through an Adaro config option so that caching could be turned on/off depending on whether the server is running on development/production mode etc. It would be VERY handy.
Actually I kind of believe it was that way in earlier versions of Adaro, but the 'cache' option does not work any longer.

**Comment by aredridel** [comment]
Indeed -- adaro2 is a rewrite, but the dust API change has thrown me. I'll be making things more dev-friendly soon.

**Comment by AleCaste** [comment]
Excellent. Great work indeed.
We'll continue our work while the new changes in Adaro get ready. Also we have noticed Makara is requiring Adaro version "~0.1.7" so it's pointless to use Makara right now. We'll wait until you update these two modules since after a lot of evaluation Adaro+Makara is the combination we definitely want in our system.

**Comment by aredridel** [comment]
What about makara are you after? My goal is to completely erase any need for makara (and in fact, in current kraken, makara is broken into many modules)

**Comment by aredridel** [comment]
Also, just FYI, note that the adaro@2 releases are prerelease.  0.1.x are the currently stable branch.

**Comment by AleCaste** [comment]
Is Makara going to be discontinued or what do you mean by erasing any need for Makara?
We need a translation module and since we like dust engine and properties files (we come from the Java world) Makara seems like a perfect fit.
And yes, we used Adaro 0.1.x and Makara 1.0 in some tests apps and they worked just fine.

**Comment by aredridel** [comment]
It will, though if I have my name, Makara will be the name for the i18n project within Kraken

**Comment by aredridel** [comment]
The modern parts of makara are localizr, grunt-localizr, file-resolver, engine-munger, karka, and adaro.

**Comment by AleCaste** [comment]
Great. We made our app work with engine-munger.
krakenjs.com still points at Makara as the module to use for localization. That should be updated if the new bet is on engine-munger.
By the way we need the @useContent helper for our templates...do you know if the dust-makara-helpers module is compatible with engine-munger?

**Comment by aredridel** [comment]
Nope. That'll be part of the new world order. You could hack it together but it'd be a giant ball of configuration.

**Comment by AleCaste** [comment]
Damn it! Well... we'll see what we can do. Thanks!

**Comment by aredridel** [comment]
Sure thing! Sorry you've found a transitional mess. I'm working to clean up these loose ends and give a new coherent system.
