### ISSUE TITLE
whitespace config option does not work?

### ISSUE THREAD

**Issue by tkambler** [krakenjs/adaro#68]
```
app.engine('dust', adaro.dust({
    'whitespace': true
}));
app.set('view engine', 'dust');
```

This should disable whitespace compression, correct? Isn't doing so for me.

**Comment by aredridel** [comment]
Which version of adaro and of dust?

**Comment by tkambler** [comment]
```
    "adaro": "~0.1.10",
    "dustjs-linkedin": "~2.6.0",
    "dustjs-helpers": "~1.6.3"
```

**Comment by aredridel** [comment]
Yeah. This version of dust only uses its internal configuration and can't see adaro's. You can require `dustjs-linkedin` and set the config as `dust.config.whitespace`. Sorry it's messy! Adaro has been hit by non-public but exposed API changes in the last several releases. I believe this worked before but doesn't now.

**Comment by sethkinast** [comment]
`dust.config.whitespace` was added in 2.5.0 and hasn't changed since. If adaro is passing options to dust, that one will be respected.

**Comment by aredridel** [comment]
Yeah. It's not. However, I'd like to support this for adaro 1.0, which I just made keep its instance of dust separate, if all goes well.
