### ISSUE TITLE
Document dust filter initialization using helpers: property.

### ISSUE THREAD

**Issue by Ndrou** [krakenjs/adaro#81]
It would be nice if it was possible to add an option to initialize dust filters same as helpers.

**Comment by shaoner** [comment]
Hi,
You can use the "helpers" options for filters as well, it just give you the dust instance, so you're free to do:

``` js
{ 
    helpers: [ 
        function (dust) { 
            dust.filters.myFilter = function (value) { return value; };
        } 
    ] 
}
```

**Comment by aredridel** [comment]
Well pointed out, @shaoner. I'll have to get that into the docs.
