### ISSUE TITLE
Possible to stream without repeated code?

### ISSUE THREAD

**Issue by elliotlings** [krakenjs/adaro#82]
If I understand correctly, if I want to stream my views, I have to do the following:

``` javascript
res.render('index', {
    "async": doSomethingAsync
}, function (err, stream) {
    stream.pipe(res);
});
```

is there anyway the 3rd argument can be moved elsewhere so I don't have to repeat it for every time I call res.render?

**Comment by aredridel** [comment]
It does that internally already.

**Comment by jknight12882** [comment]
Following up on this - can you point to where exactly this is happening internally? As far as I can tell, you do in fact have to manually pipe the dust stream to the express response stream by hand
