### ISSUE TITLE
Documentation is inaccurate / missing

### ISSUE THREAD

**Issue by tkambler** [krakenjs/adaro#85]
Adaro's documentation needs some serious work, IMO.

For starters - could someone please provide a simple, fully-functional example that demonstrates the use of layouts within the context of an Express application that _doesn't_ use Kraken? [Nothing I've tried](https://gist.github.com/tkambler/bb60a52abc57c2dbf7af) seems to work.

You start off by talking about requiring `adaro` and passing it to Express with various options for defining helpers, etc... Great, I'm with you. Afterwards, when you begin discussing [layouts](https://github.com/krakenjs/adaro#layout-optional-string-sets-default-template-to-use-for-layout), you reference the `dust.render()` method. Isn't the point of adaro to provide integration with Express via `res.render()`? And where did the `dust` var come from to begin with? It's not explained at all. Did you require `dustjs-linked`? And this `layout` option... Are we supposed to pass that into the initial factory method - `adaro.dust()`? Or are we supposed to pass that for each individual render call?

Take this for example:

```
dust.render('index', { layout: 'myLayout' }, ...);
```

What exactly is `...`? This is not explained. Does the second parameter get passed to the template as a context? Or do we have to pass in another object for that?

**Comment by aredridel** [comment]
Which version of Adaro are you using and reading the docs for? (I've done some massive rewriting to accommodate dust 2.7). You may be seeing a mismatch there, and I want to make sure I give you the right advice.

However: the `layout` option is being removed. Use blocks (`{<body}....{/body}` and base templates (`{> "myLayoutName"}`) in your template.

**Comment by tkambler** [comment]
```
  "dependencies": {
    "adaro": "^1.0.0-15",
    "dustjs-helpers": "^1.7.1",
    "dustjs-linkedin": "^2.7.2",
    "express": "^4.12.4"
  }
```

Also... Does anyone still hang around in Kraken's IRC channel? It's #kraken - right?

**Comment by aredridel** [comment]
I don't hang out there -- `#kraken` is mostly for a bitcoin-related project called Kraken.

However, http://nodeslackers.io/ has a #kraken channel I hang out in, along with a few other folks who use it.

**Comment by aredridel** [comment]
Okay, just so you're aware, that's a prerelease version of Adaro. I think it's done good things, but I'm still finding the last holes in the docs and fixing them up. Notice the `-15` on the version number and you can get a sense of how many iterations I've had to do.

**Comment by tkambler** [comment]
Did you just change the default branch for this repo back to 1.x?

**Comment by aredridel** [comment]
No, but I changed the default branch for this repo to 1.x. ;-)

**Comment by aredridel** [comment]
The major PR for the 1.x branch is https://github.com/krakenjs/adaro/pull/84 -- hoping to get that merged soon. That will solidify the 1.x feature set, I hope.

**Comment by aredridel** [comment]
(you can see the current docs for -15 on the next branch)

**Comment by tkambler** [comment]
OK - switching to these deps solves the problems:

```
    "adaro": "0.1.10",
    "dustjs-helpers": "~1.6.3",
    "dustjs-linkedin": "~2.6.0"
```

Thanks - things work as expected now. I still feel like most of the issues I pointed out regarding documentation still apply (references to `dust.render()`, ambiguous instructions as to how `layout` gets passed in, etc...). Hopefully these will be addressed in the upcoming update. If not, I'll submit a PR.

**Comment by aredridel** [comment]
Excellent. It's going to be a big change, thanks to Dust breaking what makes adaro adaro in 0.1.x. But I think it's going to be a good change.

**Comment by aredridel** [comment]
And passing in layout will go away in 1.x, as I mentioned. So be prepared!
