### ISSUE TITLE
Consider not requiring a .properties file for each .dust file

### ISSUE THREAD

**Issue by grawk** [krakenjs/adaro#89]
Currently it would be required to have a .properties file for each .dust file. Some files may get their content entirely from their data model, or else have no localizable content.

**Comment by aredridel** [comment]
I was torn on this -- quality of error reporting vs quality of development experience.

If one disables the autoloading of default content in `dust-makara-helpers`, you can have templates without default content, since you use `@useContent` to be explicit.

**Comment by aredridel** [comment]
(and the module that triggers this error is `dust-makara-helpers`, not `adaro`)

**Comment by grawk** [comment]
OK. Sorry for ready-fire-aim. I'll reopen there.
